# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import mgmt_pb2 as mgmt__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mgmt_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MgmtStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/halbot.mgmt.Mgmt/Health',
                request_serializer=mgmt__pb2.HealthRequest.SerializeToString,
                response_deserializer=mgmt__pb2.HealthReply.FromString,
                _registered_method=True)
        self.GetConfig = channel.unary_unary(
                '/halbot.mgmt.Mgmt/GetConfig',
                request_serializer=mgmt__pb2.GetConfigRequest.SerializeToString,
                response_deserializer=mgmt__pb2.ConfigState.FromString,
                _registered_method=True)
        self.UpdateConfig = channel.unary_unary(
                '/halbot.mgmt.Mgmt/UpdateConfig',
                request_serializer=mgmt__pb2.UpdateConfigRequest.SerializeToString,
                response_deserializer=mgmt__pb2.ConfigState.FromString,
                _registered_method=True)
        self.PersistConfig = channel.unary_unary(
                '/halbot.mgmt.Mgmt/PersistConfig',
                request_serializer=mgmt__pb2.PersistConfigRequest.SerializeToString,
                response_deserializer=mgmt__pb2.ConfigState.FromString,
                _registered_method=True)
        self.ResetConfig = channel.unary_unary(
                '/halbot.mgmt.Mgmt/ResetConfig',
                request_serializer=mgmt__pb2.ResetConfigRequest.SerializeToString,
                response_deserializer=mgmt__pb2.ConfigState.FromString,
                _registered_method=True)


class MgmtServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PersistConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MgmtServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=mgmt__pb2.HealthRequest.FromString,
                    response_serializer=mgmt__pb2.HealthReply.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=mgmt__pb2.GetConfigRequest.FromString,
                    response_serializer=mgmt__pb2.ConfigState.SerializeToString,
            ),
            'UpdateConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConfig,
                    request_deserializer=mgmt__pb2.UpdateConfigRequest.FromString,
                    response_serializer=mgmt__pb2.ConfigState.SerializeToString,
            ),
            'PersistConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.PersistConfig,
                    request_deserializer=mgmt__pb2.PersistConfigRequest.FromString,
                    response_serializer=mgmt__pb2.ConfigState.SerializeToString,
            ),
            'ResetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetConfig,
                    request_deserializer=mgmt__pb2.ResetConfigRequest.FromString,
                    response_serializer=mgmt__pb2.ConfigState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'halbot.mgmt.Mgmt', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('halbot.mgmt.Mgmt', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Mgmt(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/halbot.mgmt.Mgmt/Health',
            mgmt__pb2.HealthRequest.SerializeToString,
            mgmt__pb2.HealthReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/halbot.mgmt.Mgmt/GetConfig',
            mgmt__pb2.GetConfigRequest.SerializeToString,
            mgmt__pb2.ConfigState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/halbot.mgmt.Mgmt/UpdateConfig',
            mgmt__pb2.UpdateConfigRequest.SerializeToString,
            mgmt__pb2.ConfigState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PersistConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/halbot.mgmt.Mgmt/PersistConfig',
            mgmt__pb2.PersistConfigRequest.SerializeToString,
            mgmt__pb2.ConfigState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/halbot.mgmt.Mgmt/ResetConfig',
            mgmt__pb2.ResetConfigRequest.SerializeToString,
            mgmt__pb2.ConfigState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
