# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mgmt.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'mgmt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmgmt.proto\x12\x0bhalbot.mgmt\"\x0f\n\rHealthRequest\"=\n\x0bHealthReply\x12\x16\n\x0euptime_seconds\x18\x01 \x01(\x01\x12\x16\n\x0e\x64\x61\x65mon_version\x18\x02 \x01(\t\"G\n\x0bStringValue\x12\r\n\x05value\x18\x01 \x01(\t\x12)\n\x06source\x18\x02 \x01(\x0e\x32\x19.halbot.mgmt.ConfigSource\":\n\x0b\x43onfigState\x12+\n\tlog_level\x18\x01 \x01(\x0b\x32\x18.halbot.mgmt.StringValue\"\x12\n\x10GetConfigRequest\"?\n\x13UpdateConfigRequest\x12(\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x18.halbot.mgmt.ConfigState\"&\n\x14PersistConfigRequest\x12\x0e\n\x06\x66ields\x18\x01 \x03(\t\"$\n\x12ResetConfigRequest\x12\x0e\n\x06\x66ields\x18\x01 \x03(\t*\x88\x01\n\x0c\x43onfigSource\x12\x1d\n\x19\x43ONFIG_SOURCE_UNSPECIFIED\x10\x00\x12\x19\n\x15\x43ONFIG_SOURCE_DEFAULT\x10\x01\x12\x1a\n\x16\x43ONFIG_SOURCE_REGISTRY\x10\x02\x12\"\n\x1e\x43ONFIG_SOURCE_RUNTIME_OVERRIDE\x10\x03\x32\xf0\x02\n\x04Mgmt\x12>\n\x06Health\x12\x1a.halbot.mgmt.HealthRequest\x1a\x18.halbot.mgmt.HealthReply\x12\x44\n\tGetConfig\x12\x1d.halbot.mgmt.GetConfigRequest\x1a\x18.halbot.mgmt.ConfigState\x12J\n\x0cUpdateConfig\x12 .halbot.mgmt.UpdateConfigRequest\x1a\x18.halbot.mgmt.ConfigState\x12L\n\rPersistConfig\x12!.halbot.mgmt.PersistConfigRequest\x1a\x18.halbot.mgmt.ConfigState\x12H\n\x0bResetConfig\x12\x1f.halbot.mgmt.ResetConfigRequest\x1a\x18.halbot.mgmt.ConfigStateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mgmt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONFIGSOURCE']._serialized_start=404
  _globals['_CONFIGSOURCE']._serialized_end=540
  _globals['_HEALTHREQUEST']._serialized_start=27
  _globals['_HEALTHREQUEST']._serialized_end=42
  _globals['_HEALTHREPLY']._serialized_start=44
  _globals['_HEALTHREPLY']._serialized_end=105
  _globals['_STRINGVALUE']._serialized_start=107
  _globals['_STRINGVALUE']._serialized_end=178
  _globals['_CONFIGSTATE']._serialized_start=180
  _globals['_CONFIGSTATE']._serialized_end=238
  _globals['_GETCONFIGREQUEST']._serialized_start=240
  _globals['_GETCONFIGREQUEST']._serialized_end=258
  _globals['_UPDATECONFIGREQUEST']._serialized_start=260
  _globals['_UPDATECONFIGREQUEST']._serialized_end=323
  _globals['_PERSISTCONFIGREQUEST']._serialized_start=325
  _globals['_PERSISTCONFIGREQUEST']._serialized_end=363
  _globals['_RESETCONFIGREQUEST']._serialized_start=365
  _globals['_RESETCONFIGREQUEST']._serialized_end=401
  _globals['_MGMT']._serialized_start=543
  _globals['_MGMT']._serialized_end=911
# @@protoc_insertion_point(module_scope)
